### ISSUE TITLE
How is django-chunkator different/better than `queryset.iterator()` ?

### ISSUE THREAD

**Issue by polinom** [novafloss/django-chunkator#39] opened 2020-03-04 15:57 UTC
How is `django-chunkator` different / better than [`queryset.iterator`](https://docs.djangoproject.com/en/2.2/ref/models/querysets/#django.db.models.query.QuerySet.iterator) ?

**Comment by k4nar** [comment] 2020-03-05 11:33
If you have server-side cursors (using Postgres or Oracle & not setting DISABLE_SERVER_SIDE_CURSORS), then the main difference is that the cursor is in the hands of the application instead of the server. It really depends on your constraints, but sometimes server side cursors can put too much strains on your DB.

If you don't have server-side cursors, then chunkator will allow you to iterate over your queryset by batch, without relying on LIMIT/OFFSET. The problem with LIMIT/OFFSET is that computing a large offset (when you're at the end of your queryset) requires the DB to go through all the previous entries. With large tables this can be a huge issue.

I haven't used `queryset.iterator` in a long time, so there might be other gotchas, I'm not sure.

**Comment by brunobord** [comment] 2020-06-18 12:27
@polinom  did that answer your question so we can close this issue?

**Comment by brunobord** [comment] 2020-12-16 16:21
it looks like the issue is closed. If not, please do not hesitate to reopen this one.

**Closed as completed by brunobord** 2020-12-16 16:21 UTC
