### ISSUE TITLE
If queryset was ordered prior to calling `chunkator` would this ordering be preserved?

### ISSUE THREAD

**Issue by polinom** [novafloss/django-chunkator#38] opened 2020-03-04 14:08 UTC
If queryset was ordered prior to calling `chunkator` would this ordering be preserved?

**Comment by k4nar** [comment] 2020-03-05 11:17
No, chunkator order the queryset by pk: https://github.com/peopledoc/django-chunkator/blob/master/chunkator/__init__.py#L27-L33

However you could the same think than chunkator with another field, given that it's unique & not nullable.

**Comment by brunobord** [comment] 2020-06-18 12:33
@polinom : do you think  we answered your question so we can close this issue?

**Comment by brunobord** [comment] 2020-12-16 16:22
it looks like the issue is closed. If not, please do not hesitate to reopen this one.

**Closed as completed by brunobord** 2020-12-16 16:22 UTC
